name: SHUTTERWHALE
favicon: null
layout_spectrum: 0.25948
typography_spectrum: 0.47682
title: SHUTTERWHALE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#26a9e1'
    - '#201e1f'
    - '#696768'
    - '#c7c5c6'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
